title: How to connect one Crumble Sparkle to a Crumble
hero_image: images/banner.png
description: How to connect one Crumble Sparkle to a Crumble
version: 4
listed: false
copyedit: false
last_tested: "2019-05-28"
steps:
  - title: How to connect one Crumble Sparkle to a Crumble
