title: Connecting a single Crumble Sparkle
hero_image: images/banner.png
description: connect-single-sparkle description
version: 4
listed: false
copyedit: false
last_tested: "2019-05-28"
steps:
  - title: Introduction
